<ul class="tabs">
    <li>
        <a href="<?php echo $this->getUrl('vendors/vendor/index'); ?>" class="tab-item-link">List Vendors</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('vendors/vendor/create'); ?>" class="tab-item-link">Add Vendor</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('vendors/product'); ?>" class="tab-item-link">Add Product</a>
    </li>
</ul>